#connect to msol
Connect-MSOLService

Get-MsolUser -UserPrincipalName "ahellier@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "awilson@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "agacitua@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "adonahe@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "archarles@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "agreen@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "anicolet@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "aluke@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "ashernandez@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "awright@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "bmoran@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "bhirtle@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "blutz@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "cmarshall@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "csalmonson@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "dtaveras@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "dbarry@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "ddiffer@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "egudjonsdottir@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "erjohannsdottir@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "ekim@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "etschoppe@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "gpastor@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "jjose@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "jhussey@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "jbarrett@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "jawang@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "jblake@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "jduras@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "joemason@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "jvornbrock@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "jhreinsson@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "jsoto-mendigorin@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "jwang@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "kamcintyre@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "krichardson@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "khartley@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "kcrawford@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "kdevlin@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "laradottir@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "lbarker@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "lmccracken@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "llukacs@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "lalonso@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "lharrington@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "msammon@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "madams@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "mcrowe@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "mholdway@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "mhuszarik@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "mbowman@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "mbenware@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "mbamberry@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "mschreiber@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "mmckenney@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "mnunez@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "mculioli@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "ngawlik@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "nescalais@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "pmcleod@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "prubin@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "rsood@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "rpettigrew@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "slewington@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "smacintyre@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "scameron@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "shergott@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "shegarty@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "smcqueen@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "shardy@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "stays@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "smcfadden@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "tellis@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "tscallen@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "tgiles@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "ttays@pursuitcollection.com" | select objectid
Get-MsolUser -UserPrincipalName "vthumlert@pursuitcollection.com" | select objectid
