#get-acl -Path | fl "location"

#USAK06-FS01 Departments
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\081220_AlaskaBoat" | fl > "C:\_Workfile\Temp\081220_AlaskaBoat.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\2017 Boat Retail" | fl > "C:\_Workfile\Temp\2017 Boat Retail.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\2017 EOS Inventory" | fl > "C:\_Workfile\Temp\2017 EOS Inventory.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\2017 Retail Binders" | fl > "C:\_Workfile\Temp\2017 Retail Binders.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\2017 Retail Freight" | fl > "C:\_Workfile\Temp\2017 Retail Freight.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\2017 Retail Pro reports" | fl > "C:\_Workfile\Temp\2017 Retail Pro reports.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\2018 DEPOSITS-KenaiFjordsTours" | fl > "C:\_Workfile\Temp\2018 DEPOSITS-KenaiFjordsTours.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\2018 Shuttle List" | fl > "C:\_Workfile\Temp\2018 Shuttle List.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Accounting NEW" | fl > "C:\_Workfile\Temp\Accounting NEW.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Accounting old" | fl > "C:\_Workfile\Temp\Accounting old.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Backup Videos" | fl > "C:\_Workfile\Temp\Backup Videos.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Brightsign 2022" | fl > "C:\_Workfile\Temp\Brightsign 2022.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Customer Incident Reports" | fl > "C:\_Workfile\Temp\Customer Incident Reports.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\DIY-IT-Printers-Shared-Drive-G-J" | fl > "C:\_Workfile\Temp\DIY-IT-Printers-Shared-Drive-G-J.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Employee Contracts" | fl > "C:\_Workfile\Temp\Employee Contracts.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Employee Incident Forms" | fl > "C:\_Workfile\Temp\Employee Incident Forms.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Employee Tracking" | fl > "C:\_Workfile\Temp\Employee Tracking.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Entry-Gate-Videos" | fl > "C:\_Workfile\Temp\Entry-Gate-Videos.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\EOM RETAIL MAY 2019" | fl > "C:\_Workfile\Temp\EOM RETAIL MAY 2019.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Facilities" | fl > "C:\_Workfile\Temp\Facilities.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Facilities - Copy" | fl > "C:\_Workfile\Temp\Facilities - Copy.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Fox Island" | fl > "C:\_Workfile\Temp\Fox Island.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Fox Island Permitting" | fl > "C:\_Workfile\Temp\Fox Island Permitting.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\GOPRO" | fl > "C:\_Workfile\Temp\GOPRO.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Groups" | fl > "C:\_Workfile\Temp\Groups.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Helly Warehouse" | fl > "C:\_Workfile\Temp\Helly Warehouse.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\HellyHansen" | fl > "C:\_Workfile\Temp\HellyHansen.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Housing Survey" | fl > "C:\_Workfile\Temp\Housing Survey.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Inventory" | fl > "C:\_Workfile\Temp\Inventory.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\IT" | fl > "C:\_Workfile\Temp\IT.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\KFT Acct. Assistant" | fl > "C:\_Workfile\Temp\KFT Acct. Assistant.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\KFT Customer Service" | fl > "C:\_Workfile\Temp\KFT Customer Service.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\KFT GS1" | fl > "C:\_Workfile\Temp\KFT GS1.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\KFTINV" | fl > "C:\_Workfile\Temp\KFTINV.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\KFTOffice" | fl > "C:\_Workfile\Temp\KFTOffice.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\kftwarehouse" | fl > "C:\_Workfile\Temp\kftwarehouse.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\MakeaWish" | fl > "C:\_Workfile\Temp\MakeaWish.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Marine Science" | fl > "C:\_Workfile\Temp\Marine Science.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\MarineOps" | fl > "C:\_Workfile\Temp\MarineOps.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Motor Vehicle Incidents" | fl > "C:\_Workfile\Temp\Motor Vehicle Incidents.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\multi unit pics" | fl > "C:\_Workfile\Temp\multi unit pics.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Ops Assistant" | fl > "C:\_Workfile\Temp\Ops Assistant.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\orca pc pics" | fl > "C:\_Workfile\Temp\orca pc pics.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\pic for cameron" | fl > "C:\_Workfile\Temp\pic for cameron.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\presence" | fl > "C:\_Workfile\Temp\presence.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Retail" | fl > "C:\_Workfile\Temp\Retail.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Retail Binders" | fl > "C:\_Workfile\Temp\Retail Binders.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\RETAIL END OF MONTH APRIL" | fl > "C:\_Workfile\Temp\RETAIL END OF MONTH APRIL.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\RETAIL SODA machine" | fl > "C:\_Workfile\Temp\RETAIL SODA machine.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\RetailManager" | fl > "C:\_Workfile\Temp\RetailManager.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\RFPs" | fl > "C:\_Workfile\Temp\RFPs.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Short Cuts" | fl > "C:\_Workfile\Temp\Short Cuts.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Statistics" | fl > "C:\_Workfile\Temp\Statistics.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\SWD-Pictures" | fl > "C:\_Workfile\Temp\SWD-Pictures.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\temprp" | fl > "C:\_Workfile\Temp\temprp.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\TRANSACTION REGISTER" | fl > "C:\_Workfile\Temp\TRANSACTION REGISTER.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Transportation" | fl > "C:\_Workfile\Temp\Transportation.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Uniforms" | fl > "C:\_Workfile\Temp\Uniforms.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Utilities" | fl > "C:\_Workfile\Temp\Utilities.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Vendor Appreciation 2017" | fl > "C:\_Workfile\Temp\Vendor Appreciation 2017.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Video" | fl > "C:\_Workfile\Temp\Video.txt"
Get-Acl -Path "\\usak06-fs01.ges.intra\Shared\Work Folder" | fl > "C:\_Workfile\Temp\Work Folder.txt"