##Take ownership of all COMMON folders on CAAB01-FS02 D:\Share\COMMON

takeown.exe /F "D:\Data\Share\COMMON\Above Banff"
takeown.exe /F "D:\Data\Share\COMMON\Accounts Receivable (Billings)"
takeown.exe /F "D:\Data\Share\COMMON\Air File"
takeown.exe /F "D:\Data\Share\COMMON\AIRPORT INTL BACKUP"
takeown.exe /F "D:\Data\Share\COMMON\Alaska for Amanda"
takeown.exe /F "D:\Data\Share\COMMON\Attraction Confirmations 2013"
takeown.exe /F "D:\Data\Share\COMMON\Attraction no-show tracking"
takeown.exe /F "D:\Data\Share\COMMON\Attractions"
takeown.exe /F "D:\Data\Share\COMMON\Banff Gondola Interp & Programming"
takeown.exe /F "D:\Data\Share\COMMON\Banff Lake Cruise"
takeown.exe /F "D:\Data\Share\COMMON\BJC 2021.2.0.1 RTPOneClient"
takeown.exe /F "D:\Data\Share\COMMON\BJC Hotel Maintenance"
takeown.exe /F "D:\Data\Share\COMMON\Capital Projects BJC"
takeown.exe /F "D:\Data\Share\COMMON\Central Reservations"
takeown.exe /F "D:\Data\Share\COMMON\Charter  Sightseeing"
takeown.exe /F "D:\Data\Share\COMMON\CHASE"
takeown.exe /F "D:\Data\Share\COMMON\Columbia Icefield"
takeown.exe /F "D:\Data\Share\COMMON\Commissions Payable (Pacific)"
takeown.exe /F "D:\Data\Share\COMMON\Crystal Reports (AR)"
takeown.exe /F "D:\Data\Share\COMMON\CSR"
takeown.exe /F "D:\Data\Share\COMMON\Driver Hiring Transportation & Icefields 2019"
takeown.exe /F "D:\Data\Share\COMMON\Experience Evals"
takeown.exe /F "D:\Data\Share\COMMON\Fiesta Photo Booth"
takeown.exe /F "D:\Data\Share\COMMON\Food & Beverage"
takeown.exe /F "D:\Data\Share\COMMON\Forecast Templates - BI360"
takeown.exe /F "D:\Data\Share\COMMON\Gateway Cash Reports"
takeown.exe /F "D:\Data\Share\COMMON\GEM Deposits"
takeown.exe /F "D:\Data\Share\COMMON\Gondola Monthly Financial Review"
takeown.exe /F "D:\Data\Share\COMMON\Gondola"
takeown.exe /F "D:\Data\Share\COMMON\Guest Experience"
takeown.exe /F "D:\Data\Share\COMMON\Health and Safety"
takeown.exe /F "D:\Data\Share\COMMON\Hiring 2015"
takeown.exe /F "D:\Data\Share\COMMON\Hospitality Programming"
takeown.exe /F "D:\Data\Share\COMMON\Incentive Model ER"
takeown.exe /F "D:\Data\Share\COMMON\Insurance"
takeown.exe /F "D:\Data\Share\COMMON\Interpretive Training"
takeown.exe /F "D:\Data\Share\COMMON\Inventory"
takeown.exe /F "D:\Data\Share\COMMON\Jasper"
takeown.exe /F "D:\Data\Share\COMMON\log"
takeown.exe /F "D:\Data\Share\COMMON\Login"
takeown.exe /F "D:\Data\Share\COMMON\LOGOS - Mexico Tour Ops"
takeown.exe /F "D:\Data\Share\COMMON\Maestro"
takeown.exe /F "D:\Data\Share\COMMON\Maintenance"
takeown.exe /F "D:\Data\Share\COMMON\Maligne Valley ops"
takeown.exe /F "D:\Data\Share\COMMON\Mandarin Readiness Strategies 2019"
takeown.exe /F "D:\Data\Share\COMMON\Marketing Reports"
takeown.exe /F "D:\Data\Share\COMMON\Marketing Resources"
takeown.exe /F "D:\Data\Share\COMMON\Monthend Journal Entries"
takeown.exe /F "D:\Data\Share\COMMON\Newsletter"
takeown.exe /F "D:\Data\Share\COMMON\Notes IDs"
takeown.exe /F "D:\Data\Share\COMMON\oracle"
takeown.exe /F "D:\Data\Share\COMMON\oracle_driver"
takeown.exe /F "D:\Data\Share\COMMON\PAYABLES"
takeown.exe /F "D:\Data\Share\COMMON\PBAscent"
takeown.exe /F "D:\Data\Share\COMMON\Phone System"
takeown.exe /F "D:\Data\Share\COMMON\Pictures"
takeown.exe /F "D:\Data\Share\COMMON\PowerBI"
takeown.exe /F "D:\Data\Share\COMMON\print_drivers"
takeown.exe /F "D:\Data\Share\COMMON\Retail Pro"
takeown.exe /F "D:\Data\Share\COMMON\RETAIL-PHOTO"
takeown.exe /F "D:\Data\Share\COMMON\Revenue Management"
takeown.exe /F "D:\Data\Share\COMMON\RMV"
takeown.exe /F "D:\Data\Share\COMMON\RTP Lite (MLC)"
takeown.exe /F "D:\Data\Share\COMMON\RTP Planning"
takeown.exe /F "D:\Data\Share\COMMON\RTP Sky NL breakdown"
takeown.exe /F "D:\Data\Share\COMMON\Sales & Marketing"
takeown.exe /F "D:\Data\Share\COMMON\Staff Accom"
takeown.exe /F "D:\Data\Share\COMMON\switchboard"
takeown.exe /F "D:\Data\Share\COMMON\TPC 2019"
takeown.exe /F "D:\Data\Share\COMMON\Transportation"
takeown.exe /F "D:\Data\Share\COMMON\Viad Strategy Session - 03-APR-2012"
takeown.exe /F "D:\Data\Share\COMMON\viad"
takeown.exe /F "D:\Data\Share\COMMON\WebcamStills"
takeown.exe /F "D:\Data\Share\COMMON\Wholesale"
takeown.exe /F "D:\Data\Share\COMMON\zzArchive"